# Generated by Django 5.0.7 on 2024-07-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
